export const AR: Record<string, string> = {
 "Academic Research Assistant": "مساعد البحث الأكاديمي",
 "Project": "المشروع",
 "Search papers, journals, manuscripts…": "ابحث في الأوراق والمجلات والمخطوطات…",
 "All systems ready": "كل الأنظمة جاهزة",
 "Ollama unavailable": "Ollama غير متاح",
 "Mockup · sample data": "نموذج أولي · بيانات تجريبية",
 "Workspace": "مساحة العمل",
 "Dashboard": "لوحة التحكم",
 "Papers": "الأوراق العلمية",
 "Journals": "المجلات",
 "Manuscripts": "المخطوطات",
 "Review": "المراجعة",
 "Compliance": "الامتثال",
 "Reports": "التقارير",
 "Models & System": "النماذج والنظام",
 "Research Overview": "نظرة عامة على البحث",
 "What is happening in your project right now": "ما الذي يحدث في مشروعك الآن",
 "Upload paper": "رفع ورقة",
 "Continue writing": "متابعة الكتابة",
 "Active projects": "مشاريع نشطة",
 "Journal profiles": "ملفات المجلات",
 "Done": "تم",
 "In progress": "قيد التنفيذ",
 "Next": "التالي",
 "Import papers": "استيراد الأوراق",
 "Build knowledge base": "بناء قاعدة المعرفة",
 "Ask the literature": "اسأل الأدبيات",
 "Write manuscript": "كتابة المخطوطة",
 "Check journal fit": "فحص ملاءمة المجلة",
 "Final submission review": "المراجعة النهائية للتقديم",
 "Attention required": "يتطلب انتباهك",
 "Open compliance": "فتح الامتثال",
 "Structured Methods section is missing": "قسم المنهجية المنظم مفقود",
 "Blocking": "مانع",
 "2 unsupported claims in the Discussion": "ادعاءان بلا دعم في المناقشة",
 "No direct evidence in the knowledge base": "لا يوجد دليل مباشر في قاعدة المعرفة",
 "Critical": "حرج",
 "Warning": "تحذير",
 "Suggestion": "الاقتراح",
 "1 missing citation in the Introduction": "استشهاد مفقود في المقدمة",
 "Journal profile needs verification": "ملف المجلة يحتاج إلى تحقق",
 "Recent papers": "أحدث الأوراق",
 "All papers": "كل الأوراق",
 "Ready": "جاهز",
 "Processing": "قيد المعالجة",
 "Recent activity": "النشاط الأخير",
 "Paper imported": "تم استيراد ورقة",
 "PDF processed": "تمت معالجة PDF",
 "Manuscript analyzed": "تم تحليل المخطوطة",
 "Journal requirements updated": "تم تحديث متطلبات المجلة",
 "Processing queue": "قائمة المعالجة",
 "Extracting sections": "استخراج الأقسام",
 "Generating embeddings": "توليد التضمينات",
 "Completed": "مكتمل",
 "System status": "حالة النظام",
 "Details": "التفاصيل",
 "Backend": "الخادم",
 "Online": "متصل",
 "Database": "قاعدة البيانات",
 "Connected": "متصل",
 "Vector DB": "قاعدة المتجهات",
 "AI model status": "حالة نماذج الذكاء الاصطناعي",
 "Academic writing": "الكتابة الأكاديمية",
 "Embeddings": "التضمينات",
 "Journal evaluation": "تقييم المجلة",
 "Your research library": "مكتبتك البحثية",
 "Import from URL": "استيراد من رابط",
 "Upload PDF": "رفع PDF",
 "Drop PDF files here": "أسقط ملفات PDF هنا",
 "or use Upload PDF. Text, sections and embeddings are prepared automatically.": "أو استخدم رفع PDF. تُجهَّز النصوص والأقسام والتضمينات تلقائيًا.",
 "Search title, author, DOI": "ابحث بالعنوان أو المؤلف أو DOI",
 "All": "الكل",
 "Needs attention": "يحتاج إلى معالجة",
 "Title": "العنوان",
 "Year": "السنة",
 "Journal": "المجلة",
 "DOI": "DOI",
 "Tags": "الوسوم",
 "Status": "الحالة",
 "Analyze": "تحليل",
 "Failed": "فشل",
 "Retry": "إعادة المحاولة",
 "Find in paper": "بحث داخل الورقة",
 "Summarize": "تلخيص",
 "Sections": "الأقسام",
 "Abstract": "الملخص",
 "Introduction": "المقدمة",
 "Methods": "المنهجية",
 "Results": "النتائج",
 "Discussion": "المناقشة",
 "References": "المراجع",
 "Conclusion": "الخاتمة",
 "Ask AI": "اسأل الذكاء الاصطناعي",
 "Add to notes": "أضف إلى الملاحظات",
 "Ask about": "اسأل عن",
 "Current paper": "الورقة الحالية",
 "Selected papers": "الأوراق المحددة",
 "Current journal": "المجلة الحالية",
 "Current manuscript": "المخطوطة الحالية",
 "Entire knowledge base": "قاعدة المعرفة كاملة",
 "General AI": "ذكاء اصطناعي عام",
 "Direct evidence": "دليل مباشر",
 "Inference": "استنتاج",
 "General knowledge": "معرفة عامة",
 "Paper": "الورقة",
 "Page": "الصفحة",
 "Section": "القسم",
 "Copy": "نسخ",
 "Regenerate": "إعادة التوليد",
 "Extract results": "استخراج النتائج",
 "Extract methodology": "استخراج المنهجية",
 "Extract limitations": "استخراج القيود",
 "Ask about this paper": "اسأل عن هذه الورقة",
 "Focus AI assistant": "التركيز على المساعد",
 "The pipeline resembles common surface-based tools, but the paper never states which one. Treat this as a guess, not a finding.": "يشبه مسار المعالجة أدوات شائعة، لكن الورقة لا تذكر أيها. اعتبر هذا تخمينًا لا نتيجة.",
 "Re-verify sources": "إعادة التحقق من المصادر",
 "Last verified": "آخر تحقق",
 "Overview": "نظرة عامة",
 "Requirements": "المتطلبات",
 "Style": "الأسلوب",
 "Rejection patterns": "أنماط الرفض",
 "Example papers": "أوراق نموذجية",
 "Sources": "المصادر",
 "Compliance history": "سجل الامتثال",
 "Scope": "النطاق",
 "Official guidelines": "الإرشادات الرسمية",
 "Profile summary": "ملخص الملف",
 "Observed patterns": "الأنماط المرصودة",
 "Official requirement": "متطلب رسمي",
 "Observed pattern": "نمط مرصود",
 "Model assessment": "تقييم النموذج",
 "Stated by the journal": "تنص عليه المجلة",
 "Seen in published papers": "مرصود في الأوراق المنشورة",
 "Inferred by the AI, not journal policy": "استنتاج الذكاء الاصطناعي وليس سياسة المجلة",
 "Requirement": "المتطلب",
 "Type": "النوع",
 "Basis": "الأساس",
 "Source": "المصدر",
 "Verified": "التحقق",
 "Mandatory": "إلزامي",
 "Recommended": "موصى به",
 "Quality": "جودة",
 "Met": "مستوفى",
 "Not met": "غير مستوفى",
 "Needs review": "يحتاج إلى مراجعة",
 "Style guide": "دليل الأسلوب",
 "Target journal": "المجلة المستهدفة",
 "words": "كلمة",
 "Draft": "مسودة",
 "Version history": "سجل الإصدارات",
 "Run compliance check": "تشغيل فحص الامتثال",
 "Outline": "المخطط",
 "Saved": "تم الحفظ",
 "Suggestions": "الاقتراحات",
 "Evidence": "الأدلة",
 "Issues": "المشكلات",
 "Selected: Discussion, paragraph 2": "المحدد: المناقشة، الفقرة 2",
 "Improve clarity": "تحسين الوضوح",
 "Grammar": "القواعد",
 "More concise": "أكثر إيجازًا",
 "Expand": "توسيع",
 "Check consistency": "فحص الاتساق",
 "Find unsupported claim": "البحث عن ادعاء بلا دعم",
 "Suggest citation": "اقتراح استشهاد",
 "Compare with journal style": "مقارنة بأسلوب المجلة",
 "Original": "الأصل",
 "Why": "السبب",
 "Accept": "قبول",
 "Reject": "رفض",
 "Nothing changes until you accept": "لا يتغير شيء حتى تقبل",
 "Applied. The Discussion text has been updated.": "تم التطبيق. تم تحديث نص المناقشة.",
 "Rejected. The original text is unchanged.": "تم الرفض. النص الأصلي كما هو.",
 "Undo": "تراجع",
 "The original claims causation and has no supporting source in your knowledge base.": "يدّعي النص الأصلي علاقة سببية ولا يوجد له مصدر داعم في قاعدة المعرفة.",
 "Submission readiness": "جاهزية التقديم",
 "NOT READY": "غير جاهز",
 "2 blocking issues remain.": "تبقى مشكلتان مانعتان.",
 "Journal Compliance": "امتثال المجلة",
 "Export report": "تصدير التقرير",
 "This status covers known journal requirements and automated checks only. It does not predict acceptance.": "تشمل هذه الحالة متطلبات المجلة المعروفة والفحوص الآلية فقط، ولا تتنبأ بالقبول.",
 "Journal requirements checked": "تم فحص متطلبات المجلة",
 "Manuscript structure checked": "تم فحص بنية المخطوطة",
 "References checked": "تم فحص المراجع",
 "Figures checked": "تم فحص الأشكال",
 "2 blocking issues remain": "تبقى مشكلتان مانعتان",
 "Checks passed by area": "الفحوص الناجحة حسب المجال",
 "Mandatory requirements": "المتطلبات الإلزامية",
 "Scientific completeness": "الاكتمال العلمي",
 "Writing": "الكتابة",
 "Submission package": "حزمة التقديم",
 "Missing mandatory section: structured Methods": "قسم إلزامي مفقود: منهجية منظمة",
 "Data availability statement is absent": "بيان إتاحة البيانات غائب",
 "Unsupported claim: “main driver of conversion”": "ادعاء بلا دعم: «المحرك الرئيسي للتحول»",
 "Effect sizes lack confidence intervals": "أحجام التأثير بلا فترات ثقة",
 "Add a limitations paragraph heading": "أضف عنوانًا لفقرة القيود",
 "Why it matters": "لماذا يهم",
 "Location": "الموضع",
 "Suggested action": "الإجراء المقترح",
 "The journal rejects submissions that do not report scanner, sequence and acquisition parameters.": "ترفض المجلة الأوراق التي لا تذكر الجهاز والتسلسل ومعاملات الاكتساب.",
 "Add an “MRI acquisition” subsection with the parameters from the paper’s Methods.": "أضف قسمًا فرعيًا «اكتساب الرنين المغناطيسي» بالمعاملات المذكورة في المنهجية.",
 "Review suggestion": "مراجعة الاقتراح",
 "Generated analyses you can view, export and save": "تحليلات مولّدة يمكنك عرضها وتصديرها وحفظها",
 "Report": "التقرير",
 "Generated": "تاريخ الإنشاء",
 "View": "عرض",
 "Export": "تصدير",
 "Save": "حفظ",
 "Manuscript analysis": "تحليل المخطوطة",
 "Journal compliance": "امتثال المجلة",
 "Citation analysis": "تحليل الاستشهادات",
 "Evidence report": "تقرير الأدلة",
 "Rejection pattern analysis": "تحليل أنماط الرفض",
 "Final submission report": "تقرير التقديم النهائي",
 "Available after all blocking issues are resolved": "متاح بعد حل جميع المشكلات المانعة",
 "Choose which local model handles each task": "اختر النموذج المحلي المسؤول عن كل مهمة",
 "Simulate Ollama outage": "محاكاة انقطاع Ollama",
 "Restore Ollama": "استعادة Ollama",
 "Disconnected": "غير متصل",
 "The application cannot currently communicate with the local AI service. Check that Ollama is running.": "لا يستطيع التطبيق حاليًا الاتصال بخدمة الذكاء الاصطناعي المحلية. تأكد من أن Ollama يعمل.",
 "Technical details": "التفاصيل التقنية",
 "Role": "الدور",
 "Model": "النموذج",
 "Context": "السياق",
 "Memory": "الذاكرة",
 "Speed": "السرعة",
 "General chat": "محادثة عامة",
 "Literature analysis": "تحليل الأدبيات",
 "Summarization": "التلخيص",
 "Classification": "التصنيف",
 "Embedding": "التضمين",
 "Storage": "التخزين",
 "Type a command or search": "اكتب أمرًا أو ابحث",
 "Search papers": "البحث في الأوراق",
 "Open manuscript": "فتح المخطوطة",
 "Analyze manuscript": "تحليل المخطوطة",
 "Open journal": "فتح مجلة",
 "Switch AI model": "تبديل نموذج الذكاء الاصطناعي",
 "Open settings": "فتح الإعدادات",
 "Unavailable": "غير متاح",
 "Theme": "المظهر"
};
