lines = []
lines.append('"""Tests for Phase 11."""')
lines.append('from __future__ import annotations')
lines.append('')
lines.append('import json')
lines.append('import sys')
lines.append('import os')
lines.append('sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))')
lines.append('')
lines.append('import pytest')
lines.append('from fastapi.testclient import TestClient')
lines.append('')
lines.append('from app.main import app')
lines.append('')
lines.append('client = TestClient(app)')
lines.append('')
lines.append('')
lines.append('def test_llm_service_json_extraction():')
lines.append('    from app.services.llm_service import LLMService')
lines.append('    service = LLMService.__new__(LLMService)')
lines.append("    assert service._extract_json('{\"key\": \"value\"}') == {\"key\": \"value\"}")
lines.append('    with pytest.raises(ValueError):')
lines.append("        service._extract_json('not json at all')")

with open('tests/test_manuscript_ai.py', 'w', encoding='utf-8', newline='\n') as f:
    for line in lines:
        f.write(line + '\n')
print('done')
