"""Add embedding_vector to document_chunks

Revision ID: 4b9bfad7d407
Revises: 
Create Date: 2026-10-03 19:15:02.161263

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b9bfad7d407'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_vector', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'embedding_vector')
    # ### end Alembic commands ###
