"""add journal columns

Revision ID: f893456d2edf
Revises: 4b9bfad7d407
Create Date: 2026-10-03 22:22:01.155190

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f893456d2edf'
down_revision: Union[str, None] = '4b9bfad7d407'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('journals', sa.Column('rejection_patterns', sa.Text(), nullable=True))
    op.add_column('journals', sa.Column('article_types', sa.Text(), nullable=True))
    op.add_column('journals', sa.Column('word_limits', sa.Text(), nullable=True))
    op.add_column('journals', sa.Column('reference_style', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('journals', 'reference_style')
    op.drop_column('journals', 'word_limits')
    op.drop_column('journals', 'article_types')
    op.drop_column('journals', 'rejection_patterns')
    # ### end Alembic commands ###
